/* include/libintrin_config_internal.h.  Generated by configure.  */
/* include/libintrin_config_internal.h.in.  Generated from configure.ac by autoheader.  */

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "bjoo@jlab.org"

/* Define to the full name of this package. */
#define PACKAGE_NAME "libintrin"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "libintrin 0.0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "libintrin"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.0.1"
