#ifndef FILEDB_CONFIG_H
#define FILEDB_CONFIG_H


/* Undef the unwanted from the environment -- eg the compiler command line */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

/* Include the stuff generated by autoconf */
#include "filedb_config_internal.h"

/* Prefix everything with FILEDB_ */
static const char* const FILEDB_PACKAGE(PACKAGE);
static const char* const FILEDB_PACKAGE_BUGREPORT(PACKAGE_BUGREPORT);
static const char* const FILEDB_PACKAGE_NAME(PACKAGE_NAME);
static const char* const FILEDB_PACKAGE_STRING(PACKAGE_STRING);
static const char* const FILEDB_PACKAGE_TARNAME(PACKAGE_TARNAME);
static const char* const FILEDB_PACKAGE_VERSION(PACKAGE_VERSION);
static const char* const FILEDB_VERSION(VERSION);


/* Undef the unwanted */
#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION
#endif

