Summary: The QDP++ System
Name: qdp++
Version: 1.21.3
Release: 1
License: Special JLAB License
Group: Development/Libraries
URL: http://www.usqcd.org/usqcd-docs/qdp++/
Source0: %{name}-%{version}.tar.gz
AutoReqProv: no
%description
This is a build of the QDP++ System for Pentium IV or higher

%prep
%setup -q

%build
mkdir -p build ; pushd build
../configure --prefix=/opt/scidac/qdp-1.21.3-scalar-single-sse --enable-parallel-arch=scalar --enable-sse2 CXXFLAGS="-O2 -finline-limit=50000 -msse -march=pentium4" CFLAGS="-O2 -msse -march=pentium4" 
gmake -j 4
popd

%install
pushd build
make install
popd
rm -rf ./build
mkdir -p /opt/scidac/qdp-1.21.3-scalar-single-sse/src
cp -r * /opt/scidac/qdp-1.21.3-scalar-single-sse/src

%clean
rm -rf $RPM_BUILD_ROOT


%files
/opt/scidac/qdp-1.21.3-scalar-single-sse
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/qio-convert-mesh-pfs
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/lime_extract_type
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/qio-convert-mesh-singlefs
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/qdp++-config
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/qio-config
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/print_xpath
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/print_nodeset
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/replace_xpath
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/lime_unpack
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/lime_pack
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/lime_contents
/opt/scidac/qdp-1.21.3-scalar-single-sse/bin/lime_extract_record
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib/liblime.a
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib/libqdp.a
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib/libxmlWriter.a
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib/libXPathReader.a
/opt/scidac/qdp-1.21.3-scalar-single-sse/lib/libqio.a
/opt/scidac/qdp-1.21.3-scalar-single-sse/src
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/ChangeLog
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/install-all.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/build2m.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_scalar.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_scalar-double.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/build3g.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/install2m.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/build_k2.6.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-gm.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-gigE.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-single.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-gigE-double.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/install.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-gm-double.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/install3g.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/build.csh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-p4.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/jlab/config_qdp++_parscalar-gm-intel.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_scalar.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_parscalarvec-single.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_parscalar-single.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_scalar-double.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_scalarvec.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/cygwin/config_qdp++_parscalar-mpi.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/BlueGene
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/BlueGene/build_functions.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/BlueGene/build_all.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/NERSC
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/NERSC/configure_qdp++_wilson.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/NERSC/configure_libxml.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end/build_functions.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end/setup.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end/configure_qdp++_ddr.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end/build_all.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/ED_qcdocfe_AIX_front_end/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/configure_qdp++.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/configure_qdp++_bagelblas_edram.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/configure_qdp++_ddr.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/configure_qdp++_bagelblas_ddr.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/CU_qcdochost0/configure_libxml.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/BNL_qcdoc_AIX_front_end
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/BNL_qcdoc_AIX_front_end/build_functions.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/install_scripts/QCDOC/BNL_qcdoc_AIX_front_end/build_all.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/config
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/config/mkinstalldirs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/config/install-sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/config/missing
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/config/depcomp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/qdp++-config.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/INSTALL_EXAMPLES
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/AUTHORS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/configure.ac
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/acinclude.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/ChangeLog.html
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarvec_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_byteorder.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_qdpio.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_default_allocator.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_crc32.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_xmlio.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_layout.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarvec_init.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalarvec_init.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalar_init.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalar_layout.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarsite_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_strnlen.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_qio_strings.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarsite_sse.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_iogauge.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_profile.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalar_init.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_stopwatch.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalar_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalarvec_layout.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_util.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_filebuf.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_subset.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_io.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_map.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_binx.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_qcdoc_allocator.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarvecsite_sse.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_random.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarvecsite_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalarvec_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_qmp_extensions.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalarvec_layout.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalar_layout.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_stdio.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_parscalar_global_sum.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/lib/qdp_scalar_specific.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/COPYING
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/TODOLIST
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/autom4te.cache
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/autom4te.cache/output.0
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/autom4te.cache/requests
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/autom4te.cache/traces.0
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/ChangeLog
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config/mkinstalldirs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config/install-sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config/compile
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config/missing
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/config/depcomp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc/qiodoc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/doc/qio_2p0.tex
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/AUTHORS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/bin
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/bin/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/bin/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/bin/qio-config.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/configure.ac
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/acinclude.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/ChangeLog.html
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml/DML_utils.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml/DML_parscalar.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml/DML_route.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml/DML_crc32.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/dml/DML_scalar.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_info.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_utils.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_read_record_info.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_close_read.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_next_record.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_host_utils.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_open_read.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_close_write.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_write.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_host_file_conversion.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_open_write.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_read_record_data.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_read.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/qio/QIO_string.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/lrl
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/lrl/LRL_main.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/lrl/LRL_dummy.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/lib/xml/XML_string.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/COPYING
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/ChangeLog
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/config
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/config/mkinstalldirs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/config/install-sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/config/missing
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/config/depcomp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/doc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/doc/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/doc/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/doc/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/doc/lime_1p2.tex
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/AUTHORS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/configure.ac
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/acinclude.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/ChangeLog.html
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/lime_fseeko.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/lime_header.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/lime_reader.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/lime_utils.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/lib/lime_writer.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/COPYING
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/INSTALL
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_writer_test1.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_extract_record.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_pack.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_unpack.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_contents.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/examples/lime_extract_type.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/configure
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/NEWS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/aclocal.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_binary_header.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_fixed_types.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_config_internal.h.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_header.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_fseeko.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_utils.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/other_libs/c-lime/include/lime_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/INSTALL
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/layout_hyper_mesh.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/layout_hyper.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test4.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-convert-mesh.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-host-test.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-host-test2.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test1.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test2.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test-util.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test8.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-convert-mesh.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-host-test1.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-convert-mesh-pfs.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test5.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test3.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-convert-mesh-singlefs.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test7.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/examples/qio-test6.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/configure
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/NEWS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/aclocal.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qio_stdint.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qio_config_internal.h.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/crc32.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qio_string.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/lrl.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/dml.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qio_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/qio/include/qioxml.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/ChangeLog
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/ToDoList
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/config
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/config/mkinstalldirs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/config/install-sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/config/missing
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/config/depcomp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/AUTHORS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/configure.ac
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/acinclude.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/xml_simplewriter.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/attribute.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/xml_struct_writer.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/lib/basic_xpath_reader.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/COPYING
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/INSTALL
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/basic_xpath_reader_test2.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/schema_test-v0.5.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/edwards.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/simple_writer_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/foo.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/simple_schema_writer_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/struct_writer_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/print_nodeset.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/schema_writer_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/print_xpath.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/xpath_reader_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/basic_xpath_reader_test3.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/replace_xpath.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/examples/basic_xpath_reader_test.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/configure
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/NEWS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/aclocal.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_schemawriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_simpleschemawriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_array2d.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xpath_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/basic_xpath_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_document.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_array.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_array_type.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_tcomplex.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_struct_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_simplewriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_array_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/other_libs/xpath_reader/include/xml_attribute.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/INSTALL
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_exotic.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/formfac_w.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/testOpenPartFile.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.intel-scalar.input1
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_nersc.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/blas1.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/reunit.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_partfile.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.intel-scalar.output2
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/jlab_sse.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_exotic.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_blas_g5_2.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_transpose_spin.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_shift.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qio.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_entry.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_nersc.cfg
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_mesplq.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_cblas.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_formfac.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/mesplq.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/blas1.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/junk.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/unittest.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_linalg.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_formfac.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/linalg1.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.intel-scalar.input2
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_skeleton.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/test_ildglat.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qdp.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/cblas1.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_blas_g5_3.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_dprec_ildg.lime
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/taproj.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_foo.input
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_mesplq.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_spectrum.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/nersc2ildg.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/file.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_remote.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.intel-scalar.output3
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/polylp.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_nml.input
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_xml.intel-scalar.output1
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_io.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_blas.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_transpose_spin.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_foo.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/baryon_w.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_dslashm.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/test_ildglat.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_spectrum.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_basic.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/rgauge.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/nersc2ildg.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/expm12.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qio.intel-scalar.lime
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_nersc.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/record.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_entry.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qio_factory.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_cugauge.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/testIONode.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_basic.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_shift.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/cblas1.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_blas_g5.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_gsum.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qdp.intel-scalar.xml
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_dslashm.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_qio.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_io.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/dslashm_w.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_binx.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/examples.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/mesons_w.cc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/linalg2.c
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/examples/t_nml.intel-scalar.output
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/QDPOps.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Join.cpp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/config
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/config/common.mk
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/config/LINUXEGCS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Join.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Options.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/OperatorDescriptor.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PeteOps.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/visitor.pl
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PeteOps.cpp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PAssert.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PrintOperators.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PAssert.cpp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Options.cpp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Header.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/Parser.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/README
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PrintList.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/DescriptorBase.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/makefile
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PeteOps.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/MakeOperators.cpp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/ClassDescriptor.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/Tools/PrintFunctions.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/makefile
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/PETE/QDPClasses.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/configure
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/mkdocs.sh
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/manual.tex
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/main.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/implementation.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/doxygen.cfg
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/build.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/header.html
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/intro.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/qiodetail.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/spin.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/io.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/functions.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/datatypes.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/usr/qio.dox
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/ref
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/ref/doxygen.cfg
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/docs/quick_ref.tex
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/NEWS
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/aclocal.m4
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_sse_intrin.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarvecsite_sse.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_byteorder.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_iogauge.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_word.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_filebuf.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primgamma.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primcolormat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_io.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarsite_generic.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_multi.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarvecsite_sse
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarvecsite_sse/qdp_scalarvecsite_sse_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarvecsite_sse/ssevec_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarvecsite_sse/qdp_scalarvecsite_sse_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_flopcount.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_specializations.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalar_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarsite_bagel_qdp.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qdptype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_subset.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_binx.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarsite_sse.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qmp_extensions.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_parscalar_global_sum.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_init.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_traits.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_util.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primspinmat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_stdio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primvector.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_singleton.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_params.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qcdoc_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_default_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primseed.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarvec_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primscalar.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_crc32.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qdpsubtype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_xmlio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_optops.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_outersubtype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qdpexpr.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primspinvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/qdp_scalarsite_sse_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_blas_vaxpy3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/qdp_scalarsite_sse_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_blas_vaypx3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_blas_vadd3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_s_m_a_mat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_adj_mat_hwvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/qdp_scalarsite_sse_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_blas_vscal3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_addvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_blas_vaxpby3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_adj_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_mult_na.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_mat_hwvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/qdp_scalarsite_sse_blas_g5_includes.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/qdp_scalarsite_sse_vector.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_sse/sse_s_m_a_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarvecsite_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarsite_pabasm.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_strnlen.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_parscalarvec_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_config_internal.h.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_bagel_qdp
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_bagel_qdp/qdp_scalarsite_bagel_qdp_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_bagel_qdp/qdp_scalarsite_bagel_qdp_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_qcdoc
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_qcdoc/qdp_scalarsite_qcdoc_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_qcdoc/qcdoc_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_qcdoc/save_fp_regs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_qcdoc/qcdoc_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_qdpio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_profile.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_layout.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_parscalar_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/TreeNodes.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/Makefile.am
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/ForEach.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/Combiners.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/CreateLeaf.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/Scalar.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/Makefile.in
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/ForEachInOrder.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/PETE.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/OperatorTags.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/TypeComputations.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/PETE/Functors.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_globalfuncs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_random.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_simpleword.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_forward.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_stopwatch.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vcaxmy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_local_sumsq.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxpy3_norm.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_local_vcdot_real.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vadd3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vcscal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxmby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxpy3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vsub.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vscal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaypx3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxmy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_adj_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_local_vcdot.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vcaxpy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_mult_na.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/qdp_scalarsite_generic_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxmby3_norm.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/qdp_scalarsite_generic_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_addvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_mult_aa.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/qdp_scalarsite_generic_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/qdp_scalarsite_generic_cblas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vcaxmby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxpby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxpby3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vaxpy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vcaxpby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vadd.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/scalarsite_generic/generic_blas_vscal_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primcolorvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_newops.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_inner.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primitive.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/QDPOperators.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_scalarsite_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_primmatrix.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_reality.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_precision.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_outer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/src/include/qdp_map.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_sse_intrin.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qio_stdint.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarvecsite_sse.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_byteorder.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_schemawriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_iogauge.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_word.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_simpleschemawriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_filebuf.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primgamma.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primcolormat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_io.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarsite_generic.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_multi.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarvecsite_sse
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarvecsite_sse/qdp_scalarvecsite_sse_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarvecsite_sse/ssevec_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarvecsite_sse/qdp_scalarvecsite_sse_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_flopcount.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_specializations.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalar_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarsite_bagel_qdp.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_qdptype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_subset.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xpath_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_binx.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarsite_sse.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_binary_header.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_init.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_traits.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_util.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primspinmat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_stdio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primvector.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/basic_xpath_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_singleton.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_params.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_qcdoc_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_default_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primseed.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_document.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarvec_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primscalar.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qio_string.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_reader.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_fixed_types.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_crc32.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_array.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_qdpsubtype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_xmlio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_optops.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_outersubtype.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_qdpexpr.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primspinvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/qdp_scalarsite_sse_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_blas_vaxpy3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/qdp_scalarsite_sse_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_blas_vaypx3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_blas_vadd3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_s_m_a_mat.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_adj_mat_hwvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/qdp_scalarsite_sse_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_blas_vscal3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_addvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_blas_vaxpby3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_adj_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_mult_na.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_mat_hwvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/qdp_scalarsite_sse_blas_g5_includes.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_sse/sse_s_m_a_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarvecsite_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lrl.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_strnlen.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_array_type.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_parscalarvec_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_bagel_qdp
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_bagel_qdp/qdp_scalarsite_bagel_qdp_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_bagel_qdp/qdp_scalarsite_bagel_qdp_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_qcdoc
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_qcdoc/qdp_scalarsite_qcdoc_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_qcdoc/qcdoc_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_qcdoc/save_fp_regs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_qcdoc/qcdoc_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_qdpio.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_profile.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_layout.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_tcomplex.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_parscalar_specific.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qio_config_internal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/TreeNodes.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/ForEach.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/Combiners.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/CreateLeaf.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/Scalar.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/ForEachInOrder.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/PETE.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/OperatorTags.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/TypeComputations.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/PETE/Functors.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_globalfuncs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/dml.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_struct_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_random.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_header.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_simpleword.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_config_internal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_allocator.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_forward.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_stopwatch.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vcaxmy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_local_sumsq.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxpy3_norm.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_local_vcdot_real.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_mult_nn.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vadd3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vcscal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxmby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxpy3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vsub.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vscal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaypx3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxmy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_adj_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_local_vcdot.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vcaxpy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_mult_na.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/qdp_scalarsite_generic_blas_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxmby3_norm.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_mat_vec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/qdp_scalarsite_generic_linalg.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_addvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_mult_aa.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/qdp_scalarsite_generic_blas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/qdp_scalarsite_generic_cblas.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_mult_an.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vcaxmby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxpby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxpby3_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vaxpy3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vcaxpby3.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vadd.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/scalarsite_generic/generic_blas_vscal_g5.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qio_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_fseeko.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primcolorvec.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_simplewriter.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_newops.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_inner.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primitive.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/QDPOperators.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_array_writer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_utils.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_scalarsite_defs.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_primmatrix.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_reality.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_precision.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/xml_attribute.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_outer.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/lime_config.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qioxml.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_config_internal.h
/opt/scidac/qdp-1.21.3-scalar-single-sse/include/qdp_map.h


%defattr(-,root,root,-)
%doc


%changelog
* Tue Oct 31 2006 Balint Joo <bjoo@qcdi02.jlab.org> - 1.21.3-1
- Initial build.

%requires: libxml2-devel >= 2.6.11
%provides: qdp++
