all: 
	echo "specify make src"

src: efindsite-1.2 efindsite-1.2-phi

efindsite-1.2.tar.gz:
	wget http://brylinski.cct.lsu.edu/sites/all/modules/pubdlcnt/pubdlcnt.php?file=/pub/codes/efindsite-1.2.tar.gz
	mv *efindsite-1.2.tar.gz efindsite-1.2.tar.gz

efindsite-1.2:
	tar -xf efindsite-1.2.tar.gz

efindsite-1.2-phi.tar.gz:
	wget http://brylinski.cct.lsu.edu/sites/all/modules/pubdlcnt/pubdlcnt.php?file=/pub/codes/efindsite-1.2-phi.tar.gz
	mv *efindsite-1.2-phi.tar.gz efindsite-1.2-phi.tar.gz

efindsite-1.2-phi:
	tar -xf efindsite-1.2-phi.tar.gz


