export MIC_ENV_PREFIX=MIC
export MIC_OMP_NUM_THREADS=240
export MIC_KMP_AFFINITY=balanced
export MIC_KMP_STACKSIZE=16m
export MIC_STACKSIZE=128M
#export MIC_USE_2MB_BUFFERS=512K
export OFFLOAD_REPORT=2
