#
# Used for making the QDPOperators.h file in the include directory.
# This file is not built into the automake system.
#
all: 
	Tools/MakeOperators --classes QDPClasses.in --operators QDPOps.in \
	--pete-ops --guard QDPOPS_H --op-tags --o QDPOperators.h
