all:
	@echo "Please use the following commands to run a GPAW example""
	@echo "    source ./0-env.sh"
	@echo "    ./1-build.sh"
	@echo "    ./2-run-host.sh"
	@echo "    ./2-run-mic.sh"
	@echo
	@echo "To clean up please use the following command:"
	@echo "    ./3-cleanup.sh"
	