#!/usr/bin/env python

import sys

# We want to accept an argument callsed --setups, but GPAW will consume
# that string from sys.argv if it can get its hands on that.  We'll therefore
# back up the argv before anything else happens
argv = sys.argv[1:]

from gpaw.utilities.kwargs import main

main(argv)
